BITMEX_EXCHANGE_ID = 'bitmex'
BINANCE_EXCHANGE_ID = 'binance'
CANDLE_TIMESTAMP_INDEX = 0
CANDLE_OPEN_PRICE_INDEX = 1
CANDLE_HIGHEST_PRICE_INDEX = 2
CANDLE_LOWEST_PRICE_INDEX = 3
CANDLE_CLOSING_PRICE_INDEX = 4
CANDLE_VOLUME_INDEX = 5

ALGORITHM_CONFIGURATION_ID_INDEX = 0
ALGORITHM_CONFIGURATION_TRADING_STATE_INDEX = 1
ALGORITHM_CONFIGURATION_ALGORITHM_NAME_INDEX = 2
ALGORITHM_CONFIGURATION_EXCHANGE_NAME_INDEX = 7
ALGORITHM_CONFIGURATION_API_KEY_INDEX = 8
ALGORITHM_CONFIGURATION_API_SECRET_INDEX = 9
ALGORITHM_CONFIGURATION_TRADING_PAIR_SYMBOL_INDEX = 10
ALGORITHM_CONFIGURATION_INDICATOR_CANDLE_DURATION_INDEX = 11
ALGORITHM_CONFIGURATION_INDICATOR_FRAME_COUNT_INDEX = 12
ALGORITHM_CONFIGURATION_BB_STANDARD_DEVIATION_INDEX = 13
ALGORITHM_CONFIGURATION_RSI_UPPER_INTENSITY_INDEX = 14
ALGORITHM_CONFIGURATION_RSI_LOWER_INTENSITY_INDEX = 15
ALGORITHM_CONFIGURATION_EXPOSURE_INDEX = 16
ALGORITHM_CONFIGURATION_EMA_SMOOTHING_FACTOR_INDEX = 17
ALGORITHM_CONFIGURATION_API_USERNAME = 18
ALGORITHM_CONFIGURATION_ALGORITHM_DESCRIPTION = 19
ALGORITHM_CONFIGURATION_WEBHOOK = 20

WEBHOOK_SETUP_ALGORITHM_CONFIGURATION_INDEX = 7

# Funding time related variables
MARKET_HALT_SECONDS_TO_FUNDING = 3600
MARKET_DEAD_STOP_SECONDS_TO_FUNDING = 900

FIRST_FUNDING_HOUR = 4
SECOND_FUNDING_HOUR = 12
THIRD_FUNDING_HOUR = 20

# System related setting variables
RETRY_LIMIT = 5
TRADE_LIMITING_SPECIFICATION_ARR = [[60, 20], [2, 4]]

# Algorithm name related variables
EMA_ALGORITHM_V1 = 'ema_v1'

BB_RSI_ALGORITHM_V1 = 'bb_rsi_v1'
BB_RSI_ALGORITHM_V2 = 'bb_rsi_v2'
BB_RSI_ALGORITHM_V3 = 'bb_rsi_v3'

PRICE_DATA_GENERATION_BASE_VERSION = 'price_data_generation'
